// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXLq8g99h-pzq379btJytvwsHstUrFca4',
    appId: '1:549410772144:web:b248427817794a78195775',
    messagingSenderId: '549410772144',
    projectId: 'flutter-firestore-22f5b',
    authDomain: 'flutter-firestore-22f5b.firebaseapp.com',
    storageBucket: 'flutter-firestore-22f5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNHyduuIvYKVQvNCXkHuihqi_bRKXjXgA',
    appId: '1:549410772144:android:abdf034416f8aca8195775',
    messagingSenderId: '549410772144',
    projectId: 'flutter-firestore-22f5b',
    storageBucket: 'flutter-firestore-22f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASKk2DQpVj4jkPXKZtOP2sECbgG4iHOJc',
    appId: '1:549410772144:ios:601ae68bc02d10c0195775',
    messagingSenderId: '549410772144',
    projectId: 'flutter-firestore-22f5b',
    storageBucket: 'flutter-firestore-22f5b.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASKk2DQpVj4jkPXKZtOP2sECbgG4iHOJc',
    appId: '1:549410772144:ios:601ae68bc02d10c0195775',
    messagingSenderId: '549410772144',
    projectId: 'flutter-firestore-22f5b',
    storageBucket: 'flutter-firestore-22f5b.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXLq8g99h-pzq379btJytvwsHstUrFca4',
    appId: '1:549410772144:web:1442c95e71b2fbba195775',
    messagingSenderId: '549410772144',
    projectId: 'flutter-firestore-22f5b',
    authDomain: 'flutter-firestore-22f5b.firebaseapp.com',
    storageBucket: 'flutter-firestore-22f5b.firebasestorage.app',
  );
}
